from PyQt5 import QtCore, QtGui, QtWidgets
from src.personaje import Personaje

class Ui_SecondWindow(object):
    
    def __init__(self, personaje: Personaje):
        self.personaje = personaje
    
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(282, 502)
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 251, 435))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 30, 0, 0)
        self.formLayout.setHorizontalSpacing(40)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label_height = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_height.setObjectName("label_height")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_height)
        self.label_mass = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_mass.setObjectName("label_mass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_mass)
        self.label_hair = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_hair.setObjectName("label_hair")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_hair)
        self.label_skin = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_skin.setObjectName("label_skin")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_skin)
        self.label_eye = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_eye.setObjectName("label_eye")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_eye)
        self.label_birth = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_birth.setObjectName("label_birth")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_birth)
        self.label_gender = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_gender.setObjectName("label_gender")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_gender)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        SecondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SecondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 282, 26))
        self.menubar.setObjectName("menubar")
        SecondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SecondWindow)
        self.statusbar.setObjectName("statusbar")
        SecondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", self.personaje.name + " :caracteristicas"))
        self.label_height.setText(_translate("SecondWindow", self.personaje.height))
        self.label_mass.setText(_translate("SecondWindow", self.personaje.mass))
        self.label_hair.setText(_translate("SecondWindow", self.personaje.hair_color))
        self.label_skin.setText(_translate("SecondWindow", self.personaje.skin_color))
        self.label_eye.setText(_translate("SecondWindow", self.personaje.eye_color))
        self.label_birth.setText(_translate("SecondWindow", self.personaje.birth_year))
        self.label_gender.setText(_translate("SecondWindow", self.personaje.gender))
        self.label.setText(_translate("SecondWindow", "height"))
        self.label_3.setText(_translate("SecondWindow", "mass"))
        self.label_4.setText(_translate("SecondWindow", "hair_color"))
        self.label_5.setText(_translate("SecondWindow", "skin_color"))
        self.label_6.setText(_translate("SecondWindow", "eye_color"))
        self.label_7.setText(_translate("SecondWindow", "birth_year"))
        self.label_8.setText(_translate("SecondWindow", "gender"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
